<?php 
extract ($_POST);

if($estado == 'PARÁ'){
$resposta = "
	<option class='para' value='' selected></option>
	<option value='LIONS CLUBE DE ABAETETUBA'>LIONS CLUBE DE ABAETETUBA</option>
	<option value='LIONS CLUBE DE ALTAMIRA'>LIONS CLUBE DE ALTAMIRA</option>
	<option value='LIONS CLUBE DE BELÉM CENTRO'>LIONS CLUBE DE BELÉM CENTRO</option>
	<option value='LIONS CLUBE DE BELÉM REPÚBLICA'>LIONS CLUBE DE BELÉM REPÚBLICA</option>
	<option value='LIONS CLUBE DE BELÉM MARCO'>LIONS CLUBE DE BELÉM MARCO</option>
	<option value='LIONS CLUBE DE BELÉM BATISTA CAMPOS'>LIONS CLUBE DE BELÉM BATISTA CAMPOS</option>
	<option value='LIONS CLUBE DE BELÉM NAZARETH'>LIONS CLUBE DE BELÉM NAZARETH</option>
	<option value='LIONS CLUBE DE BENEVIDES'>LIONS CLUBE DE BENEVIDES</option>
	<option value='LIONS CLUBE DE BRAGANÇA'>LIONS CLUBE DE BRAGANÇA</option>
	<option value='LIONS CLUBE DE BREU BRANCO'>LIONS CLUBE DE BREU BRANCO</option>
	<option value='LIONS CLUBE DE CASTANHAL'>LIONS CLUBE DE CASTANHAL</option>
	<option value='LIONS CLUBE DE CASTANHAL CRISTO REDENTOR'>LIONS CLUBE DE CASTANHAL CRISTO REDENTOR</option>
	<option value='LIONS CLUBE DE CAPITÃO POÇO'>LIONS CLUBE DE CAPITÃO POÇO</option>
	<option value='LIONS CLUBE DE DOM ELISEU'>LIONS CLUBE DE DOM ELISEU</option>
	<option value='LIONS CLUBE DE ICOARACI'>LIONS CLUBE DE ICOARACI</option>
	<option value='LIONS CLUBE DE IPIXUNA'>LIONS CLUBE DE IPIXUNA</option>
	<option value='LIONS CLUBE DE ITUPIRANGA'>LIONS CLUBE DE ITUPIRANGA</option>
	<option value='LIONS CLUBE DE JACUNDÁ CENTRO'>LIONS CLUBE DE JACUNDÁ CENTRO</option>
	<option value='LIONS CLUBE DE MARABÁ TOCANTINS'>LIONS CLUBE DE MARABÁ TOCANTINS</option>
	<option value='LIONS CLUBE DE MARABÁ'>LIONS CLUBE DE MARABÁ</option>
	<option value='LIONS CLUBE DE MARABÁ MELVIN JONES'>LIONS CLUBE DE MARABÁ MELVIN JONES</option>
	<option value='LIONS CLUBE DE MARABÁ ITACAIUNAS'>LIONS CLUBE DE MARABÁ ITACAIUNAS</option>
	<option value='LIONS CLUBE DE MOJÚ '>LIONS CLUBE DE MOJÚ </option>
	<option value='LIONS CLUBE NOVO PROGRESSO'>LIONS CLUBE NOVO PROGRESSO</option>
	<option value='LIONS CLUBE DE PARAGOMINAS '>LIONS CLUBE DE PARAGOMINAS </option>
	<option value='LIONS CLUBE DE PARAUAPEBAS'>LIONS CLUBE DE PARAUAPEBAS</option>
	<option value='LIONS CLUBE DE TAILANDIA'>LIONS CLUBE DE TAILANDIA</option>
	<option value='LIONS CLUBE DE TUCURUI'>LIONS CLUBE DE TUCURUI</option>
	<option value='LIONS CLUBE RONDON DO PARÁ RENASCER'>LIONS CLUBE RONDON DO PARÁ RENASCER</option>
	<option value='LIONS CLUBE DE PARAUAPEBAS CENTRO'>LIONS CLUBE DE PARAUAPEBAS CENTRO</option>
	<option value='LIONS CLUBE DE ITAITUBA MORAES ALMEIDA'>LIONS CLUBE DE ITAITUBA MORAES ALMEIDA</option> ";
}

if($estado == 'MARANHÃO'){
$resposta = "
	<option class='para' value='' selected></option>
	<option value='LIONS CLUBE DE CAXIAS CENTRO'>LIONS CLUBE DE CAXIAS CENTRO</option>
	<option value='LIONS CLUBE DE CODÓ'>LIONS CLUBE DE CODÓ</option>
	<option value='LIONS CLUBE DE SANTA INÊS'>LIONS CLUBE DE SANTA INÊS</option>
	<option value='LIONS CLUBE  DE SÃO LUIZ GONÇALVES DIAS'>LIONS CLUBE  DE SÃO LUIZ GONÇALVES DIAS</option>
	<option value='LIONS CLUBE DE SANTA LUZIA'>LIONS CLUBE DE SANTA LUZIA</option>
	<option value='LIONS CLUBE DE SÃO LUIS MARACANÃ'>LIONS CLUBE DE SÃO LUIS MARACANÃ</option>
	<option value='LIONS CLUBE DE SÃO LUIS SÃO FRANCISCO'>LIONS CLUBE DE SÃO LUIS SÃO FRANCISCO</option>
	<option value='LIONS CLUBE DE TIMON CENTRO'>LIONS CLUBE DE TIMON CENTRO</option>
	<option value='LIONS CLUBE DE TIMON ALVORADA'>LIONS CLUBE DE TIMON ALVORADA</option>
	<option value='LIONS CLUBE DE SANTA LUZIA'>LIONS CLUBE DE SANTA LUZIA</option>
	<option value='LIONS CLUBE DE TIMON UNIVEVERSITÁRIO'>LIONS CLUBE DE TIMON UNIVEVERSITÁRIO</option> ";
}

if($estado == 'PIAUÍ'){
$resposta = "
	<option class='para' value='' selected></option>
	<option value='LIONS CLUBE DE CAMPO MAIOR'>LIONS CLUBE DE CAMPO MAIOR</option>
	<option value='LIONS CLUBE DE CAMPO MAIOR UNIVERSITÁRIO'>LIONS CLUBE DE CAMPO MAIOR UNIVERSITÁRIO</option>
	<option value='LIONS CLUBE DE FLORIANO'>LIONS CLUBE DE FLORIANO</option>
	<option value='LIONS CLUBE DE LUÍS CORREIA'>LIONS CLUBE DE LUÍS CORREIA</option>
	<option value='LIONS CLUBE DE PARNAIBA'>LIONS CLUBE DE PARNAIBA</option>
	<option value='LIONS CLUBE DE PARNAIBA UNIVERSITÁRIO'>LIONS CLUBE DE PARNAIBA UNIVERSITÁRIO</option>
	<option value='LIONS CLUBE DE PICOS'>LIONS CLUBE DE PICOS</option>
	<option value='LIONS CLUBE DE TERESINA CENTRO'>LIONS CLUBE DE TERESINA CENTRO</option>
	<option value='LIONS CLUBE DE TERESINA JUBILEU DE OURO '>LIONS CLUBE DE TERESINA JUBILEU DE OURO </option>
	<option value='LIONS CLUBE DE TERESINA 08 DE MARÇO'>LIONS CLUBE DE TERESINA 08 DE MARÇO</option>
	<option value='LIONS CLUBE DE TERESINA AFONSO MAFRENSE'>LIONS CLUBE DE TERESINA AFONSO MAFRENSE</option>
	<option value='LIONS CLUBE DE TERESINA 08 DE OUTUBRO'>LIONS CLUBE DE TERESINA 08 DE OUTUBRO</option>
	<option value='LIONS CLUBE DE TERESINA CIDADE VERDE'>LIONS CLUBE DE TERESINA CIDADE VERDE</option>
	<option value='LIONS CLUBE DE TERESINA FREI SERAFIM'>LIONS CLUBE DE TERESINA FREI SERAFIM</option> ";
}

if($estado == 'AMAPÁ'){
$resposta = "
	<option class='para' value='' selected></option>
	<option value='LIONS CLUBE DE MACAPÁ CENTRO'>LIONS CLUBE DE MACAPÁ CENTRO</option>
	<option value='LIONS CLUBE DE MACAPÁ MARCO ZERO DO EQUADOR '>LIONS CLUBE DE MACAPÁ MARCO ZERO DO EQUADOR </option>
	<option value='LIONS CLUBE DE MACAPÁ PERIMETRAL'>LIONS CLUBE DE MACAPÁ PERIMETRAL</option>
	<option value='LIONS CLUBE DE MACAPÁ JESUS DE NAZARÉ'>LIONS CLUBE DE MACAPÁ JESUS DE NAZARÉ</option> ";
}

echo $resposta;

?>
